### ISSUE TITLE
SQL FILE MISSING

### ISSUE THREAD

**Issue by ZararAnsari** [oasiscse/online-attendance-management-system-1.0#2]
please do provide the sql file in database folder there is MD file which have info of how to configure db.

**Comment by surajkanode** [comment]
Sir provide me database file plzzz sir

**Comment by Bhumu** [comment]
Please send me the sql file to my email sir its missing to your scripts

**Comment by Bhumu** [comment]
here is my email: slazenmakita2@gmail.com
please send me the .sql file its missing

**Comment by CodeLife01** [comment]
SQL file missing...
here is my Email :- upworkcodelife@gmail.com

**Comment by D26dam** [comment]
Sql file is missing email: davididamdci@gmail.com

**Comment by D26dam** [comment]
Please can I get the sql file email: davididamdci@gmail.com

**Comment by sahasya** [comment]
sql file missing. could you please send? email: sahasyadrao09@gmail.com

**Comment by ihumaunkabir** [comment]
Hi
The *.sql dump is added on the repo. Please try to understand them for educational purpose, do not just copy and paste.
Happy Coding
