### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by akash-258** [oasiscse/online-attendance-management-system-1.0#8]
The requirements given in the project are outdated. Could you please give a specific version for the requirements tested by you, even the old versions, because in PHP 7.x some syntax like mysql_connect / mysql_select_db are not there.

**Comment by ihumaunkabir** [comment]
Hello @akash-258 
This project was implemented 3 years ago. I didn't test it since then. So there might be issues with the requirements. You can contribute to fix them. Thanks.
